FROM ros:noetic-ros-core-buster

# Setting default shell to bash
SHELL ["/bin/bash", "--login", "-c"]

# Install bootstrap tools
RUN apt-get update && apt-get install --no-install-recommends -y \
   build-essential \
   python3-rosdep \
   python3-rosinstall \
   ros-noetic-rosauth \
   ros-noetic-catkin \
   vim \
   && rm -rf /var/lib/apt/lists/*

# Install the rosbridge package so that all the dependencies are installed
RUN apt-get update && apt-get install -y\
   ros-noetic-rosauth \
   ros-noetic-rosbridge-server \
   && rm -rf /var/lib/apt/lists/*

# Remove the rosbridge package but leave all the dependencies installed
RUN apt-get remove ros-noetic-rosbridge-server -y

# Bootstrap rosdep
RUN rosdep init && \
 rosdep update --rosdistro $ROS_DISTRO

# Source the underlay workspace and add its sourcing to .bashrc
RUN source /opt/ros/noetic/setup.bash && \
   echo 'source /opt/ros/noetic/setup.bash' >> ~/.bashrc

# Set the working directory for the remainder of the file
WORKDIR /home

# Initialise a workspace
RUN mkdir -p /home/catkin_ws/src

# Copy the packages from the repository
COPY catkin_ws/src catkin_ws/src/

# Copy the convenience helper scripts
COPY helper_scripts .

# Remove the top-level CMakeLists.txt as it is a symbolic reference and should be generated by the first run of catkin_make
RUN rm catkin_ws/src/CMakeLists.txt

# Make the project
RUN cd catkin_ws && \
 catkin_make

# Add the sourcing of the overlay workspace into the .bashrc
RUN echo 'source /home/catkin_ws/devel/setup.bash' >> ~/.bashrc

# Expose the port 9090
EXPOSE 9090